spring:
  application:
    name: catalog-service

server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default 20
    keep-alive-timeout: 15s
    threads:
      max: 30 # default 200
      min-spare: 5 # default 10

