spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config: # config client uri and connections parameters
      uri: "http://localhost:8888"
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry: # retry using exponential backoff
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  mvc:
    servlet:
      path: /${app.api.version}
  threads:
    virtual:
      enabled: true # enabled/disable virtual thread, default is 'true' for spring boot 3.5

server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default 20
    keep-alive-timeout: 15s
    threads:
      max: 30 # default 200
      min-spare: 5 # default 10

pong:
  message: "POOONG"

app:
  api:
    version: 20250525 # If you are changing value here don't forget to update 'CatalogServiceApplicationTests.BASE_URL'

