spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config: # config client uri and connections parameters
      uri: "http://localhost:8888"
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry: # retry using exponential backoff
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  mvc:
    servlet:
      path: /${app.api.version}
  threads:
    virtual:
      enabled: true # enabled/disable virtual thread, default is 'true' for spring boot 3.5
  datasource:
    username: "catalog-user"
    password: "catalog-password"
    url: "jdbc:postgresql://localhost:5432/catalog_db"
    hikari:
      connection-timeout: 2000 # max time waiting to get connection from a pool
      maximum-pool-size: 5

server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default 20
    keep-alive-timeout: 15s
    threads:
      max: 30 # default 200
      min-spare: 5 # default 10
  shutdown: graceful

app:
  api:
    version: 20250525

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh

# Custom properties
pong:
  message: "POOONG"