apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  labels:
    app: catalog-db
spec:
  type: ClusterIP   # or NodePort/LoadBalancer if you want external access
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: catalog-db
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db
  labels:
    app: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: catalog-db
          image: postgres:17.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "catalog-user"
            - name: POSTGRES_PASSWORD
              value: "catalog-password"
            - name: POSTGRES_DB
              value: "catalog_db"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: catalog-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: catalog-db-storage
          persistentVolumeClaim:
            claimName: catalog-db-pvc
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
