#
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
#
name: Commit Stage

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    #
    # https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    #
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup GraalVM 24
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build, run unit and integration tests
        run: |
          chmod a+x gradlew
          ./gradlew build
